-- MADANI Leadership for Public Sector Transformation — Draft subprogram (solution_programs).
-- Generated by generate_madani.js from the client's spec. Safe to import via phpMyAdmin.
-- It stays hidden from the navbar/catalog/listings (is_published = 0) and is viewable
-- only by direct link with the preview token:
--   /solutions/<parent-slug>/madani-leadership-for-public-sector-transformation/?preview=<PREVIEW_TOKEN>
-- When the client approves, set Published = ON in Admin -> Subprograms (or is_published=1).

SET NAMES utf8mb4;

-- ⚠️ CHANGE this to the parent Program (child_solution) slug MADANI sits under
-- (as shown in Admin -> Subprograms -> "Program (parent)"):
SET @parent_slug = 'strategic-hr';

INSERT INTO solution_programs
  (child_solution_id, slug, eyebrow, title, description, banner, card_image, rating, reviews, rating_enabled, price_cents, currency, pricing_period, pricing_heading, pricing_description, registration_heading, overview, gains_heading, gains, focus_heading, focus_areas, faqs, facilitator, certification, layout_type, layout_data, is_published, is_active, sort_order)
VALUES
  ((SELECT id FROM child_solutions WHERE slug = @parent_slug AND delete_status = 0 LIMIT 1),
   'madani-leadership-for-public-sector-transformation',
   'Certified Programs',
   'MADANI Leadership for Public Sector Transformation',
   'A 5-day executive development programme designed for Malaysian government officials to strengthen leadership capability, human capital effectiveness, policy execution and future-ready governance in line with the Malaysia MADANI vision.',
   '/images/solutions/strategic-hr/banner.jpg',
   '/images/solutions/Certified-Programs/certified-1.jpg',
   NULL,
   0,
   1,
   450000,
   'USD',
   'Person',
   'Why It''s Worth',
   'A 5-day executive development programme, designed to strengthen leadership, human capital, policy execution, digital governance and national impact.',
   'MADANI Leadership for Public Sector Transformation',
   '{"title":"MADANI Leadership for Public Sector Transformation","description":"MADANI Leadership for Public Sector Transformation is a 5-day executive programme designed to strengthen leadership, human capital, policy execution and future-ready governance in line with the Malaysia MADANI vision. Grounded in integrity, trust, sustainability, innovation and compassion, the programme develops ethical leadership, accountable governance and citizen-centric public service delivery through interactive learning, case studies, peer learning and action planning.","image":"/images/solutions/strategic-hr/programme-suits.jpg"}',
   'What You''ll Gain From This Programme',
   '[{"text":"Build the capability to lead self, teams and institutions through complexity.","iconSrc":"/images/solutions/strategic-hr/1.svg"},{"text":"Manage talent, performance, workforce capability and succession more strategically.","iconSrc":"/images/solutions/strategic-hr/2.svg"},{"text":"Translate policy priorities into executable strategies and measurable outcomes.","iconSrc":"/images/solutions/strategic-hr/3.svg"},{"text":"Identify practical applications of digital technologies and AI for public-service improvement.","iconSrc":"/images/solutions/strategic-hr/4.svg"},{"text":"Strengthen integrity, risk management, sustainability and institutional resilience.","iconSrc":"/images/solutions/strategic-hr/5.svg"},{"text":"Develop practical action plans that connect leadership and institutional priorities with long-term national outcomes.","iconSrc":"/images/solutions/strategic-hr/6.svg"}]',
   'Focuses on Developing',
   '[{"title":"Senior-Level Positioning","description":"Designed for senior and high-potential public-sector leaders.","iconSrc":"/images/solutions/strategic-hr/1.svg"},{"title":"Transformational, Not Training","description":"Focused on translating leadership knowledge into practical institutional action.","iconSrc":"/images/solutions/strategic-hr/2.svg"},{"title":"Leadership & Human Capital","description":"Strengthening leadership capability and strategic management of public-sector talent.","iconSrc":"/images/solutions/strategic-hr/3.svg"},{"title":"Digital Strategies & Policy Execution","description":"Connecting digital transformation, AI and effective policy implementation.","iconSrc":"/images/solutions/strategic-hr/4.svg"},{"title":"Governance & National Impact","description":"Building integrity, resilience, sustainability and long-term public value.","iconSrc":"/images/solutions/strategic-hr/5.svg"}]',
   '[{"question":"What is the duration of the programme?","answer":"The programme is delivered over 5 days."},{"question":"Who is the programme designed for?","answer":"It is designed for Malaysian government officials, particularly senior and high-potential public servants."},{"question":"What areas does the programme cover?","answer":"The programme covers public-sector leadership, strategic human capital, policy execution, digital government and AI, citizen-centric services, governance, risk, sustainability and national impact."},{"question":"What learning methods are used?","answer":"The programme combines conceptual learning, action learning, experiential learning, executive coaching and case-based learning."}]',
   '[{"name":"Prof. Dr. Joel Farnworth","role":"Dean of Business and Management Studies, EIU-Paris","image":"/images/solutions/strategic-hr/Dr_Joel.png","bg":"/images/solutions/strategic-hr/program_facilitator_BG.png","expertise":["Human Resource Management","Leadership Development","Managerial Skills Development","Corporate Strategy Creation and Implementation","Performance Management","Strategic HRM"],"biography":["Coach and Consultant","Strategic HR Management","Impactive Leadership","Creating and Implementing Corporate Strategy","Senior Management Advisor"]}]',
   '{"badge":"Recognition of Learning","heading":"Certification\\non Successful\\nCompletion","paragraphs":["Participants who successfully complete the programme will receive certification recognising their participation and completion of the MADANI Leadership for Public Sector Transformation executive development programme."],"image":"/images/solutions/strategic-hr/certificate_image.jpg"}',
   'curriculum',
   '{"heading":"5 Days of Leadership & Transformation","badge":"5 Days","days":[{"label":"DAY 1","sessions":[{"color":"red","title":"Public Sector Leadership Excellence — Leading Self, Teams & Institutions in Government","bullets":["Contemporary leadership challenges","Adaptive and ethical leadership","Leading through complexity and ambiguity","Values-based leadership and public accountability","Leadership self-assessment"]}]},{"label":"DAY 2","sessions":[{"color":"dark","title":"Strategic Human Capital Management in Government — Building Capable, Engaged & Future-Ready Public Servants","bullets":["Strategic workforce planning","Talent and succession management","Performance and outcome-based appraisal","Multi-generational and diverse workforces","Culture and change transformation"]}]},{"label":"DAY 3","sessions":[{"color":"red","title":"Public Sector Strategy & Policy Execution — Translating Policy into Measurable Impact","bullets":["Strategy formulation and execution","Policy implementation frameworks","Whole-of-government collaboration","KPIs and performance dashboards","ASEAN public-sector reform case studies"]}]},{"label":"DAY 4","sessions":[{"color":"dark","title":"Digital Government, AI & Citizen-Centric Services — Leveraging Technology for Better Public Value","bullets":["Digital transformation in government","AI and data analytics applications","Citizen-centric digital services","Data governance, cybersecurity and ethics","Digital change and capability building"]}]},{"label":"DAY 5","sessions":[{"color":"red","title":"Governance, Risk, Sustainability & National Impact — Leading with Integrity, Resilience & Long-Term Vision","bullets":["Good governance and integrity","Risk management","Sustainability, ESG and national value","Crisis leadership and institutional resilience","Personal leadership action plan"]}]}]}',
   0,
   1,
   0);
